### ISSUE TITLE
Populating incidence matrix

### ISSUE THREAD

**Issue by apgr0ss** [ChiHangChen/LaplacianScore#1]
Hi! I'm reading through your code and paused at the following line

https://github.com/ChiHangChen/LaplacianScore/blob/c881ba531f62977bae45194fd34d24537ec10919/laplacian_score.py#L39

I believe this line populates the incidence matrix with the results of k-nearest neighbors. However, I'm not sure why you use `k_nearest_id` twice. Should it be

`edge_sparse_matrix.iloc[row_id, k_nearest_id] = 1` if we're looping through each row of the incidence matrix and populating its values? Thanks!

**Comment by ChiHangChen** [comment]
Hi Andrew, thank you for interested in my code.
I use `k_nearest_id` twice as row index and column index in `edge_sparse_matrix` because `edge_sparse_matrix` is a square matrix (has same size of row and col), so we setting this value to 1 so that we can use it for calculating `distance_matrix` [here](https://github.com/ChiHangChen/LaplacianScore/blob/c881ba531f62977bae45194fd34d24537ec10919/laplacian_score.py#L46C12-L46C12)

About the quiestion what you are asking for  **why I am not using `row_id` since we are inside the loop**, the answer is, I use it [here](https://github.com/ChiHangChen/LaplacianScore/blob/c881ba531f62977bae45194fd34d24537ec10919/laplacian_score.py#L38C13-L38C25) for getting `k_nearest_id`

Please let me know if you still have questions :D

**Comment by apgr0ss** [comment]
Ohh I see ok. Thanks for clearing that up!
